/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subject;

import session.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import util.*;

public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
    }


    
    private void clear() {
        subjectCode.setText("");
        subjectName.setText("");
        offeredYear.setText("");
        offeredSem.setText("");
        lecHrs.setText("");
        tuteHrs.setText("");
        labHrs.setText("");
        evalHrs.setText("");         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        viewAllButton = new javax.swing.JButton();
        subjectCode = new javax.swing.JTextField();
        subjectName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        offeredYear = new javax.swing.JTextField();
        offeredSem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lecHrs = new javax.swing.JTextField();
        tuteHrs = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labHrs = new javax.swing.JTextField();
        evalHrs = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        viewAllButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Subjects");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 289, 25));

        jLabel3.setText("Subject Code");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 102, -1));

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        viewAllButton.setText("View All");
        viewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewAllButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 83, -1));
        getContentPane().add(subjectCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 165, -1));
        getContentPane().add(subjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 165, -1));

        jLabel7.setText("Subject Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel8.setText("Offered Year");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 102, -1));
        getContentPane().add(offeredYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 165, -1));
        getContentPane().add(offeredSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 165, -1));

        jLabel9.setText("Offered Semester");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel10.setText("No of Lec Hrs");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 102, -1));
        getContentPane().add(lecHrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 165, -1));
        getContentPane().add(tuteHrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 165, -1));

        jLabel11.setText("No of Tute Hrs");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jLabel12.setText("No of Lab Hrs");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 102, -1));
        getContentPane().add(labHrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 165, -1));
        getContentPane().add(evalHrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 165, -1));

        jLabel13.setText("No of Evaluation Hrs");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        viewAllButton1.setText("Menu");
        viewAllButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(viewAllButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 83, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        
        if(subjectCode.getText()!=""){
                if(subjectName.getText()!=""){
                    if(offeredYear.getText()!=""){
                        if(offeredSem.getText()!=""){

                            String[] code = subjectCode.getText().toString().split("-",2);
                            String[] name = subjectName.getText().toString().split("-",2);
                            String[] year = offeredYear.getText().toString().split("-",2);
                            String[] sem = offeredSem.getText().toString().split("-",2);
                            String[] lHrs = lecHrs.getText().toString().split("-",2);
                            String[] tHrs = tuteHrs.getText().toString().split("-",2);
                            String[] lbHrs = labHrs.getText().toString().split("-",2);
                            String[] valHrs = evalHrs.getText().toString().split("-",2);
                            

                            Connection connection;
                            PreparedStatement preparedStatement;

                            try{
                                connection = DBConnect.getDBConnection();

                                preparedStatement = connection.prepareStatement("INSERT INTO subjects(`subjectCode`, `subjectName`, `offeredYear`, `sem`, `lecHrs`, `tuteHrs`, `labHrs`, `evalHrs`) VALUES (?,?,?,?,?,?,?,?)");
                                preparedStatement.setString(1, code[0]);
                                preparedStatement.setString(2, name[0]);
                                preparedStatement.setString(3, year[0]);
                                preparedStatement.setString(4, sem[0]);
                                preparedStatement.setString(5, lHrs[0]);
                                preparedStatement.setString(6, tHrs[0]);
                                preparedStatement.setString(7, lbHrs[0]);
                                preparedStatement.setString(8, valHrs[0]);
                                

                                if(!preparedStatement.execute()){
                                    JFrame f=new JFrame();  
                                    JOptionPane.showMessageDialog(f,"Insert Successful!");
                                    clear();
                                }else{
                                    JFrame f=new JFrame();  
                                    JOptionPane.showMessageDialog(f,"Insert Unsuccessful!");
                                }

                            }catch (ClassNotFoundException | SQLException  e) {
                                    System.out.println(e.getMessage());
                            }
                        }else{
                            JFrame f=new JFrame();  
                            JOptionPane.showMessageDialog(f,"Tag!");
                        }
                    }else{
                        JFrame f=new JFrame();  
                        JOptionPane.showMessageDialog(f,"Group!");
                    }
                }else{
                    JFrame f=new JFrame();  
                    JOptionPane.showMessageDialog(f,"Subject!");
                }
        }else{
            JFrame f=new JFrame();  
            JOptionPane.showMessageDialog(f,"Lecturer!");
        }
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void viewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllButtonActionPerformed
        JFrame frame = new View();
        setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_viewAllButtonActionPerformed

    private void viewAllButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllButton1ActionPerformed
        JFrame frame = new Menu.Menu();
        setVisible(false);
        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_viewAllButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JTextField evalHrs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField labHrs;
    private javax.swing.JTextField lecHrs;
    private javax.swing.JTextField offeredSem;
    private javax.swing.JTextField offeredYear;
    private javax.swing.JTextField subjectCode;
    private javax.swing.JTextField subjectName;
    private javax.swing.JTextField tuteHrs;
    private javax.swing.JButton viewAllButton;
    private javax.swing.JButton viewAllButton1;
    // End of variables declaration//GEN-END:variables

}
