/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package session;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import util.*;

public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
        setLecturers();
        setGroups();
        setTags();
        setSubject();
    }

    private void setLecturers() {
        
        Connection connection;
	PreparedStatement preparedStatement;
        
        try{
            connection = DBConnect.getDBConnection();

            preparedStatement = connection.prepareStatement("select * from lecturer");

            ResultSet rs1 = preparedStatement.executeQuery();
            
            lecturerSelect.addItem("Select a Lecturer");

            while(rs1.next())
            {
                lecturerSelect.addItem(rs1.getString(1)+"-"+rs1.getString(2));
            }
            
        }catch (ClassNotFoundException | SQLException  e) {
                System.out.println(e.getMessage());
        }
        
    }
    
    private void setGroups() {
        
        Connection connection;
	PreparedStatement preparedStatement;
        
        try{
            connection = DBConnect.getDBConnection();

            preparedStatement = connection.prepareStatement("select * from groups");

            ResultSet rs1 = preparedStatement.executeQuery();
            
            groupSelect.addItem("Select a Group");

            while(rs1.next())
            {
                groupSelect.addItem(rs1.getString(1)+"-"+rs1.getString(2));
            }
            
        }catch (ClassNotFoundException | SQLException  e) {
                System.out.println(e.getMessage());
        }
        
    }
    
    private void setSubject() {
        
        Connection connection;
	PreparedStatement preparedStatement;
        
        try{
            connection = DBConnect.getDBConnection();

            preparedStatement = connection.prepareStatement("select * from subjects");

            ResultSet rs1 = preparedStatement.executeQuery();
            
            subjectSelect.addItem("Select a Subject");

            while(rs1.next())
            {
                subjectSelect.addItem(rs1.getString(1)+"-"+rs1.getString(2));
            }
            
        }catch (ClassNotFoundException | SQLException  e) {
                System.out.println(e.getMessage());
        }
        
    }
    
    private void setTags() {
        
        Connection connection;
	PreparedStatement preparedStatement;
        
        try{
            connection = DBConnect.getDBConnection();

            preparedStatement = connection.prepareStatement("select * from tag");

            ResultSet rs1 = preparedStatement.executeQuery();
            
            tagSelect.addItem("Select a Tag");

            while(rs1.next())
            {
                tagSelect.addItem(rs1.getString(1)+"-"+rs1.getString(2));
            }
            
        }catch (ClassNotFoundException | SQLException  e) {
                System.out.println(e.getMessage());
        }
        
    }
    
    private void clear() {
        lecturerSelect.setSelectedIndex(0);
        groupSelect.setSelectedIndex(0);
        tagSelect.setSelectedIndex(0);
        subjectSelect.setSelectedIndex(0);
        studentsCount.setText("");
        duration.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDuration = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lecturerSelect = new javax.swing.JComboBox<>();
        groupSelect = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tagSelect = new javax.swing.JComboBox<>();
        createButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        subjectSelect = new javax.swing.JComboBox<>();
        viewAllButton = new javax.swing.JButton();
        studentsCount = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        viewAllButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Session");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 289, 25));

        txtDuration.setText("Lecturer");
        getContentPane().add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 72, -1));

        jLabel3.setText("No of Students");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 102, -1));

        jLabel4.setText("Group");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 72, -1));

        lecturerSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerSelectActionPerformed(evt);
            }
        });
        getContentPane().add(lecturerSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 165, -1));

        getContentPane().add(groupSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 165, -1));

        jLabel5.setText("Tag");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 72, -1));

        getContentPane().add(tagSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 165, -1));

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        jLabel6.setText("Subject");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 54, -1));

        getContentPane().add(subjectSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 165, -1));

        viewAllButton.setText("Menu");
        viewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewAllButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 83, -1));
        getContentPane().add(studentsCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 165, -1));
        getContentPane().add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 165, -1));

        jLabel7.setText("Duration");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lecturer and Tags"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 290, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Group and Subjects"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 330, 270));

        viewAllButton1.setText("View All");
        viewAllButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(viewAllButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 83, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        
        if(lecturerSelect.getSelectedIndex()!=0){
                if(subjectSelect.getSelectedIndex()!=0){
                    if(groupSelect.getSelectedIndex()!=0){
                        if(tagSelect.getSelectedIndex()!=0){

                            String[] lec = lecturerSelect.getSelectedItem().toString().split("-",2);
                            String[] tag = tagSelect.getSelectedItem().toString().split("-",2);
                            String[] group = groupSelect.getSelectedItem().toString().split("-",2);
                            String[] sub = subjectSelect.getSelectedItem().toString().split("-",2);
                            String[] stdCount = studentsCount.getText().toString().split("-",2);
                            String[] durationCount = duration.getText().toString().split("-",2);
                            

                            Connection connection;
                            PreparedStatement preparedStatement;

                            try{
                                connection = DBConnect.getDBConnection();

                                preparedStatement = connection.prepareStatement("INSERT INTO sessions(`lecId`, `tagId`, `groupId`, `subjectId`, `stdCount`, `duration`) VALUES (?,?,?,?,?,?)");
                                preparedStatement.setString(1, lec[0]);
                                preparedStatement.setString(2, tag[0]);
                                preparedStatement.setString(3, group[0]);
                                preparedStatement.setString(4, sub[0]);
                                preparedStatement.setString(5, stdCount[0]);
                                preparedStatement.setString(6, durationCount[0]);

                                if(!preparedStatement.execute()){
                                    JFrame f=new JFrame();  
                                    JOptionPane.showMessageDialog(f,"Insert Successful!");
                                    clear();
                                }else{
                                    JFrame f=new JFrame();  
                                    JOptionPane.showMessageDialog(f,"Insert Unsuccessful!");
                                }

                            }catch (ClassNotFoundException | SQLException  e) {
                                    System.out.println(e.getMessage());
                            }
                        }else{
                            JFrame f=new JFrame();  
                            JOptionPane.showMessageDialog(f,"Tag!");
                        }
                    }else{
                        JFrame f=new JFrame();  
                        JOptionPane.showMessageDialog(f,"Group!");
                    }
                }else{
                    JFrame f=new JFrame();  
                    JOptionPane.showMessageDialog(f,"Subject!");
                }
        }else{
            JFrame f=new JFrame();  
            JOptionPane.showMessageDialog(f,"Lecturer!");
        }
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void viewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllButtonActionPerformed
        JFrame frame = new Menu.Menu();
        setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_viewAllButtonActionPerformed

    private void lecturerSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerSelectActionPerformed

    private void viewAllButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllButton1ActionPerformed
        JFrame frame = new View();
        setVisible(false);
        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_viewAllButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JTextField duration;
    private javax.swing.JComboBox<String> groupSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> lecturerSelect;
    private javax.swing.JTextField studentsCount;
    private javax.swing.JComboBox<String> subjectSelect;
    private javax.swing.JComboBox<String> tagSelect;
    private javax.swing.JLabel txtDuration;
    private javax.swing.JButton viewAllButton;
    private javax.swing.JButton viewAllButton1;
    // End of variables declaration//GEN-END:variables

}
